#!/usr/bin/env python3
"""Regenerate outputs/taxonomy/class_axes_v2.yaml — OWNER-FINAL record.

Protocol v2 (docs/taxonomy/PROTOCOL_v2_PROPOSAL.md) passed the fresh-context
acceptance gate 2026-07-16 (rev.3); the owner then reviewed ALL 39 classes in
the viewer and signed off the same evening (two correction exports, both
folded; fold reports in outputs/taxonomy/). This script embeds that final
validated table verbatim so the annotation record is reproducible from git.

Standing exceptions (2): plasma_explosion (overlay + scene_swap=True) and
portal (cover + scene_swap=False) are owner-validated but violate the SS5.1
implication table; they carry owner_ruling=True as a visible marker until the
owner harmonizes them (mechanism or swap — one click each in the viewer).

Counts: transform 17 / overlay 12 (add 6, state 5, remove 1) / cover 4 / traverse 6 / cut 0.

Usage: python scripts/build_class_axes_v2.py
"""
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("needs pyyaml (research env)")

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "outputs/taxonomy/class_axes_v2.yaml"

CLASSES = {
    "air_bending": {
        "clips_viewed": ['air_bending_0', 'air_bending_2', 'air_bending_3'],
        "mechanism": 'transform',
        "overlay_direction": None,
        "scene_swap": True,
        "sidedness": 'two_sided',
        "camera_defining": True,
        "stylization": False,
        "middle_only": True,
        "subject_anchored": True,
        "owner_ruling": False,
        "sidedness_conflict": False,
        "cam_recheck": False,
        "validated": True,
        "notes": 'subjects dissolve into cotton-smoke which reforms as B (owner-ruled); cam: owner set y in v1 pass - re-judge under locked-off test',
        "v1_mechanism": 'occlusion',
    },
    "animalization": {
        "clips_viewed": ['animalization_0', 'animalization_4', 'animalization_7'],
        "mechanism": 'transform',
        "overlay_direction": None,
        "scene_swap": False,
        "sidedness": 'A_only',
        "camera_defining": False,
        "stylization": False,
        "middle_only": True,
        "subject_anchored": True,
        "owner_ruling": False,
        "sidedness_conflict": False,
        "cam_recheck": False,
        "validated": True,
        "notes": 'body re-renders in place into animal; transient ring',
        "v1_mechanism": 'morph',
    },
    "color_rain": {
        "clips_viewed": ['color_rain_0', 'color_rain_5', 'color_rain_8'],
        "mechanism": 'overlay',
        "overlay_direction": 'state',
        "scene_swap": False,
        "sidedness": 'A_only',
        "camera_defining": False,
        "stylization": True,
        "middle_only": True,
        "subject_anchored": False,
        "owner_ruling": False,
        "sidedness_conflict": False,
        "cam_recheck": False,
        "validated": True,
        "notes": 'liquid drenches subject; grade persists',
        "v1_mechanism": 'morph',
    },
    "cotton_cloud": {
        "clips_viewed": ['cotton_cloud_0', 'cotton_cloud_4', 'cotton_cloud_8'],
        "mechanism": 'overlay',
        "overlay_direction": 'add',
        "scene_swap": False,
        "sidedness": 'A_only',
        "camera_defining": False,
        "stylization": False,
        "middle_only": True,
        "subject_anchored": False,
        "owner_ruling": False,
        "sidedness_conflict": False,
        "cam_recheck": False,
        "validated": True,
        "notes": 'cotton fills scene around untouched subject',
        "v1_mechanism": 'morph',
    },
    "display_transition": {
        "clips_viewed": ['display_transition_1', 'display_transition_2', 'display_transition_3'],
        "mechanism": 'cover',
        "overlay_direction": None,
        "scene_swap": True,
        "sidedness": 'two_sided',
        "camera_defining": True,
        "stylization": False,
        "middle_only": True,
        "subject_anchored": False,
        "owner_ruling": False,
        "sidedness_conflict": False,
        "cam_recheck": False,
        "validated": True,
        "notes": 'held-up screen fills frame; B = screen interior (RULING: ratify interior clause; is monitor in first panel? middle_only provisional n)',
        "v1_mechanism": 'occlusion',
    },
    "earth_element": {
        "clips_viewed": ['earth_element_0', 'earth_element_3', 'earth_element_6'],
        "mechanism": 'transform',
        "overlay_direction": None,
        "scene_swap": False,
        "sidedness": 'A_only',
        "camera_defining": True,
        "stylization": False,
        "middle_only": True,
        "subject_anchored": True,
        "owner_ruling": False,
        "sidedness_conflict": False,
        "cam_recheck": False,
        "validated": True,
        "conflict_resolved": 'owner 2026-07-16',
        "notes": 'body cracks into rock in place',
        "v1_mechanism": 'morph',
    },
    "earth_wave": {
        "clips_viewed": ['earth_wave_0', 'earth_wave_2', 'earth_wave_4'],
        "mechanism": 'transform',
        "overlay_direction": None,
        "scene_swap": True,
        "sidedness": 'two_sided',
        "camera_defining": True,
        "stylization": False,
        "middle_only": True,
        "subject_anchored": True,
        "owner_ruling": False,
        "sidedness_conflict": False,
        "cam_recheck": False,
        "validated": True,
        "conflict_resolved": 'owner 2026-07-16',
        "notes": 'sand wave wraps body (RULING: becomes element -> transform, or hosts it -> overlay-state)',
        "v1_mechanism": 'morph',
    },
    "fire_element": {
        "clips_viewed": ['fire_element_0', 'fire_element_2', 'fire_element_4'],
        "mechanism": 'transform',
        "overlay_direction": None,
        "scene_swap": False,
        "sidedness": 'A_only',
        "camera_defining": False,
        "stylization": False,
        "middle_only": False,
        "subject_anchored": True,
        "owner_ruling": False,
        "sidedness_conflict": False,
        "cam_recheck": False,
        "validated": True,
        "notes": 'fire manifests on/around posed subject (RULING: accrual or substitution?)',
        "v1_mechanism": 'morph',
    },
    "firelava": {
        "clips_viewed": ['firelava_0', 'firelava_3', 'firelava_5'],
        "mechanism": 'transform',
        "overlay_direction": None,
        "scene_swap": True,
        "sidedness": 'two_sided',
        "camera_defining": True,
        "stylization": False,
        "middle_only": True,
        "subject_anchored": True,
        "owner_ruling": False,
        "sidedness_conflict": False,
        "cam_recheck": False,
        "validated": True,
        "notes": 'fire wall sweeps over the silhouette (no visible conversion) during tracked shot; reveal',
        "v1_mechanism": 'occlusion',
    },
    "flame": {
        "clips_viewed": ['flame_transition_0', 'flame_transition_1'],
        "mechanism": 'cover',
        "overlay_direction": None,
        "scene_swap": True,
        "sidedness": 'two_sided',
        "camera_defining": False,
        "stylization": False,
        "middle_only": True,
        "subject_anchored": True,
        "owner_ruling": False,
        "sidedness_conflict": False,
        "cam_recheck": False,
        "validated": True,
        "notes": 'fire -> full-frame whiteout -> recedes off different subject/set',
        "v1_mechanism": 'occlusion',
    },
    "flying_cam_transition": {
        "clips_viewed": ['flying_cam_transition_1', 'flying_cam_transition_3', 'flying_cam_transition_4'],
        "mechanism": 'traverse',
        "overlay_direction": None,
        "scene_swap": True,
        "sidedness": 'two_sided',
        "camera_defining": True,
        "stylization": False,
        "middle_only": False,
        "subject_anchored": False,
        "owner_ruling": False,
        "sidedness_conflict": False,
        "cam_recheck": False,
        "validated": True,
        "conflict_resolved": 'owner 2026-07-16',
        "notes": 'filmstrip-verified: doorway rises from desert sand; camera walks through into living room; no covering matter at handoff',
        "v1_mechanism": 'occlusion',
    },
    "gas_transformation": {
        "clips_viewed": ['gas_transformation_0', 'gas_transformation_5', 'gas_transformation_9'],
        "mechanism": 'transform',
        "overlay_direction": None,
        "scene_swap": False,
        "sidedness": 'A_only',
        "camera_defining": False,
        "stylization": False,
        "middle_only": True,
        "subject_anchored": True,
        "owner_ruling": False,
        "sidedness_conflict": False,
        "cam_recheck": False,
        "validated": True,
        "notes": 'body dissolves into gas with correspondence (conversion, dispersal-to-absence)',
        "v1_mechanism": 'morph',
    },
    "giant_grab": {
        "clips_viewed": ['giant_grab_0', 'giant_grab_2', 'giant_grab_4'],
        "mechanism": 'overlay',
        "overlay_direction": 'remove',
        "scene_swap": False,
        "sidedness": 'two_sided',
        "camera_defining": False,
        "stylization": False,
        "middle_only": False,
        "subject_anchored": True,
        "owner_ruling": False,
        "sidedness_conflict": False,
        "cam_recheck": False,
        "validated": True,
        "conflict_resolved": 'owner 2026-07-16',
        "notes": 'inserted hand drags subject out; scene persists; hand re-enters',
        "v1_mechanism": 'morph',
    },
    "hero_flight": {
        "clips_viewed": ['hero_flight_0', 'hero_flight_5', 'hero_flight_9'],
        "mechanism": 'traverse',
        "overlay_direction": None,
        "scene_swap": True,
        "sidedness": 'two_sided',
        "camera_defining": True,
        "stylization": False,
        "middle_only": False,
        "subject_anchored": True,
        "owner_ruling": False,
        "sidedness_conflict": False,
        "cam_recheck": False,
        "validated": True,
        "conflict_resolved": 'owner 2026-07-16',
        "notes": 'camera follows the launch into sustained flight persisting into B window (advisors read two_sided; owner rules)',
        "v1_mechanism": 'traversal',
    },
    "hole_transition": {
        "clips_viewed": ['hole_transition_0', 'hole_transition_1'],
        "mechanism": 'cover',
        "overlay_direction": None,
        "scene_swap": True,
        "sidedness": 'two_sided',
        "camera_defining": True,
        "stylization": False,
        "middle_only": True,
        "subject_anchored": False,
        "owner_ruling": False,
        "sidedness_conflict": False,
        "cam_recheck": False,
        "validated": True,
        "conflict_resolved": 'owner 2026-07-16',
        "notes": "camera zooms THROUGH an open ring/aperture into B's actual space (passage, not picture)",
        "v1_mechanism": 'occlusion',
    },
    "illustration_scene": {
        "clips_viewed": ['illustration_scene_0', 'illustration_scene_5', 'illustration_scene_9'],
        "mechanism": 'overlay',
        "overlay_direction": 'state',
        "scene_swap": False,
        "sidedness": 'A_only',
        "camera_defining": False,
        "stylization": True,
        "middle_only": False,
        "subject_anchored": False,
        "owner_ruling": False,
        "sidedness_conflict": False,
        "cam_recheck": False,
        "validated": True,
        "notes": 'photoreal -> flat illustration re-render in place',
        "v1_mechanism": 'morph',
    },
    "jump_transition": {
        "clips_viewed": ['jump_transition_1'],
        "mechanism": 'traverse',
        "overlay_direction": None,
        "scene_swap": True,
        "sidedness": 'two_sided',
        "camera_defining": True,
        "stylization": False,
        "middle_only": True,
        "subject_anchored": True,
        "owner_ruling": False,
        "sidedness_conflict": False,
        "cam_recheck": False,
        "validated": True,
        "notes": 'camera follows jump arc to a different place/outfit',
        "v1_mechanism": 'traversal',
    },
    "live_concert": {
        "clips_viewed": ['live_concert_0', 'live_concert_4', 'live_concert_7'],
        "mechanism": 'traverse',
        "overlay_direction": None,
        "scene_swap": True,
        "sidedness": 'A_only',
        "camera_defining": True,
        "stylization": False,
        "middle_only": False,
        "subject_anchored": False,
        "owner_ruling": False,
        "sidedness_conflict": False,
        "cam_recheck": False,
        "validated": True,
        "conflict_resolved": 'owner 2026-07-16',
        "notes": 'filmstrip-verified: backstage close-up pulls back through stage haze to festival wide (roster all-dup handled separately)',
        "v1_mechanism": 'traversal',
    },
    "luminous_gaze": {
        "clips_viewed": ['luminous_gaze_0', 'luminous_gaze_2', 'luminous_gaze_3'],
        "mechanism": 'transform',
        "overlay_direction": None,
        "scene_swap": False,
        "sidedness": 'A_only',
        "camera_defining": False,
        "stylization": True,
        "middle_only": False,
        "subject_anchored": True,
        "owner_ruling": False,
        "sidedness_conflict": False,
        "cam_recheck": False,
        "validated": True,
        "notes": 'eyes ignite; storm + rim-light accrue over persisting subject/scene',
        "v1_mechanism": 'morph',
    },
    "melt_transition": {
        "clips_viewed": ['melt_transition_1', 'melt_transition_3', 'melt_transition_4'],
        "mechanism": 'transform',
        "overlay_direction": None,
        "scene_swap": True,
        "sidedness": 'two_sided',
        "camera_defining": False,
        "stylization": False,
        "middle_only": True,
        "subject_anchored": True,
        "owner_ruling": False,
        "sidedness_conflict": False,
        "cam_recheck": False,
        "validated": True,
        "notes": "prop-derived melt covers frame; trace persists into B's first frames (mid=y assumes trace clears before final ~1s window - confirm on video)",
        "v1_mechanism": 'occlusion',
    },
    "money_rain": {
        "clips_viewed": ['money_rain_0', 'money_rain_3', 'money_rain_7'],
        "mechanism": 'overlay',
        "overlay_direction": 'add',
        "scene_swap": False,
        "sidedness": 'A_only',
        "camera_defining": False,
        "stylization": False,
        "middle_only": False,
        "subject_anchored": False,
        "owner_ruling": False,
        "sidedness_conflict": False,
        "cam_recheck": False,
        "validated": True,
        "notes": 'bills fall into persistent scene',
        "v1_mechanism": 'morph',
    },
    "monstrosity": {
        "clips_viewed": ['monstrosity_0', 'monstrosity_1', 'monstrosity_2'],
        "mechanism": 'overlay',
        "overlay_direction": 'add',
        "scene_swap": False,
        "sidedness": 'A_only',
        "camera_defining": True,
        "stylization": False,
        "middle_only": False,
        "subject_anchored": False,
        "owner_ruling": False,
        "sidedness_conflict": False,
        "cam_recheck": False,
        "validated": True,
        "notes": 'creature grows in background; scene persists',
        "v1_mechanism": 'morph',
    },
    "mystification": {
        "clips_viewed": ['mystification_0', 'mystification_3', 'mystification_5'],
        "mechanism": 'transform',
        "overlay_direction": None,
        "scene_swap": False,
        "sidedness": 'A_only',
        "camera_defining": False,
        "stylization": False,
        "middle_only": True,
        "subject_anchored": True,
        "owner_ruling": False,
        "sidedness_conflict": False,
        "cam_recheck": False,
        "validated": True,
        "notes": 'subject dissolves into colored smoke (conversion, dispersal-to-absence)',
        "v1_mechanism": 'morph',
    },
    "nature_bloom": {
        "clips_viewed": ['nature_bloom_0', 'nature_bloom_2'],
        "mechanism": 'overlay',
        "overlay_direction": 'add',
        "scene_swap": False,
        "sidedness": 'A_only',
        "camera_defining": False,
        "stylization": False,
        "middle_only": True,
        "subject_anchored": False,
        "owner_ruling": False,
        "sidedness_conflict": False,
        "cam_recheck": False,
        "validated": True,
        "notes": 'flowers grow into background',
        "v1_mechanism": 'morph',
    },
    "plasma_explosion": {
        "clips_viewed": ['plasma_explosion_0', 'plasma_explosion_2', 'plasma_explosion_4'],
        "mechanism": 'overlay',
        "overlay_direction": 'add',
        "scene_swap": True,
        "sidedness": 'A_only',
        "camera_defining": True,
        "stylization": False,
        "middle_only": True,
        "subject_anchored": True,
        "owner_ruling": True,
        "sidedness_conflict": False,
        "cam_recheck": False,
        "validated": True,
        "notes": 'CONSISTENCY 5.1 VIOLATION (post-validation): mechanism=overlay requires scene_swap=False (same scene +/- content) - fix one of the two :: | same intersection throughout; explosion cloud added, persists; cam=y arguable under locked-off test - re-judge with air_bending',
        "v1_mechanism": 'occlusion',
    },
    "polygon": {
        "clips_viewed": ['polygon_0', 'polygon_4', 'polygon_8'],
        "mechanism": 'overlay',
        "overlay_direction": 'state',
        "scene_swap": False,
        "sidedness": 'A_only',
        "camera_defining": False,
        "stylization": True,
        "middle_only": False,
        "subject_anchored": False,
        "owner_ruling": False,
        "sidedness_conflict": False,
        "cam_recheck": False,
        "validated": True,
        "notes": 'whole frame restyles photo -> white low-poly; cam flips to F under locked-off test',
        "v1_mechanism": 'traversal',
    },
    "portal": {
        "clips_viewed": ['portal_0', 'portal_2', 'portal_9'],
        "mechanism": 'cover',
        "overlay_direction": None,
        "scene_swap": False,
        "sidedness": 'A_only',
        "camera_defining": False,
        "stylization": False,
        "middle_only": True,
        "subject_anchored": True,
        "owner_ruling": True,
        "sidedness_conflict": False,
        "cam_recheck": False,
        "validated": True,
        "notes": 'CONSISTENCY 5.1 VIOLATION (post-validation): mechanism=cover requires scene_swap=True - fix one of the two :: | portal opens at subject, removes them, vanishes; street persists empty (corpus: clip 0 is cartoon - replace exemplar)',
        "v1_mechanism": 'occlusion',
    },
    "raven_transition": {
        "clips_viewed": ['raven_transition_0', 'raven_transition_2', 'raven_transition_3'],
        "mechanism": 'transform',
        "overlay_direction": None,
        "scene_swap": True,
        "sidedness": 'two_sided',
        "camera_defining": True,
        "stylization": False,
        "middle_only": True,
        "subject_anchored": True,
        "owner_ruling": False,
        "sidedness_conflict": False,
        "cam_recheck": False,
        "validated": True,
        "notes": 'raven wall covers; stray birds persist into B',
        "v1_mechanism": 'occlusion',
    },
    "run_set_on_fire": {
        "clips_viewed": ['action_run_setonfire_6', 'action_run_setonfire_7'],
        "mechanism": 'transform',
        "overlay_direction": None,
        "scene_swap": False,
        "sidedness": 'A_only',
        "camera_defining": True,
        "stylization": False,
        "middle_only": False,
        "subject_anchored": True,
        "owner_ruling": False,
        "sidedness_conflict": False,
        "cam_recheck": False,
        "validated": True,
        "notes": 'runner catches fire mid-run; same run, same alley; cam=y arguable under locked-off test - re-judge with air_bending',
        "v1_mechanism": 'morph',
    },
    "saint_glow": {
        "clips_viewed": ['saint_glow_0', 'saint_glow_2', 'saint_glow_3'],
        "mechanism": 'overlay',
        "overlay_direction": 'add',
        "scene_swap": False,
        "sidedness": 'A_only',
        "camera_defining": False,
        "stylization": False,
        "middle_only": False,
        "subject_anchored": True,
        "owner_ruling": False,
        "sidedness_conflict": False,
        "cam_recheck": False,
        "validated": True,
        "notes": 'halo forms around subject; subject unchanged',
        "v1_mechanism": 'morph',
    },
    "sakura_petals": {
        "clips_viewed": ['sakura_petals_0', 'sakura_petals_2'],
        "mechanism": 'transform',
        "overlay_direction": None,
        "scene_swap": False,
        "sidedness": 'A_only',
        "camera_defining": False,
        "stylization": False,
        "middle_only": True,
        "subject_anchored": True,
        "owner_ruling": False,
        "sidedness_conflict": False,
        "cam_recheck": False,
        "validated": True,
        "notes": 'RULING: conflicting filmstrip reads - external petal swarm covering subject (overlay-remove) vs suit eroding INTO petals (conversion -> transform)',
        "v1_mechanism": 'occlusion',
    },
    "seamless_transition": {
        "clips_viewed": ['seamless_transition_0'],
        "mechanism": 'traverse',
        "overlay_direction": None,
        "scene_swap": True,
        "sidedness": 'two_sided',
        "camera_defining": True,
        "stylization": False,
        "middle_only": False,
        "subject_anchored": False,
        "owner_ruling": False,
        "sidedness_conflict": False,
        "cam_recheck": False,
        "validated": True,
        "notes": 'hidden edit: walk-out, empty beats, walk-in different room; camera static; sidedness convention needed (effect in neither window)',
        "v1_mechanism": 'traversal',
    },
    "shadow": {
        "clips_viewed": ['shadow_0', 'shadow_2', 'shadow_9'],
        "mechanism": 'transform',
        "overlay_direction": None,
        "scene_swap": False,
        "sidedness": 'A_only',
        "camera_defining": False,
        "stylization": False,
        "middle_only": True,
        "subject_anchored": True,
        "owner_ruling": False,
        "sidedness_conflict": False,
        "cam_recheck": False,
        "validated": True,
        "notes": 'subject becomes a living shadow (conversion visible)',
        "v1_mechanism": 'morph',
    },
    "shadow_smoke": {
        "clips_viewed": ['shadow_smoke_0', 'shadow_smoke_5', 'shadow_smoke_9'],
        "mechanism": 'transform',
        "overlay_direction": None,
        "scene_swap": True,
        "sidedness": 'two_sided',
        "camera_defining": True,
        "stylization": False,
        "middle_only": True,
        "subject_anchored": True,
        "owner_ruling": False,
        "sidedness_conflict": False,
        "cam_recheck": False,
        "validated": True,
        "notes": 'body-derived smoke covers frame, clears to new scene (RULING: merely clears -> cover, or reforms into B -> transform, air_bending precedent)',
        "v1_mechanism": 'occlusion',
    },
    "super_fast_run": {
        "clips_viewed": ['super_fast_run_0', 'super_fast_run_4', 'super_fast_run_9'],
        "mechanism": 'traverse',
        "overlay_direction": None,
        "scene_swap": True,
        "sidedness": 'A_only',
        "camera_defining": True,
        "stylization": False,
        "middle_only": False,
        "subject_anchored": True,
        "owner_ruling": False,
        "sidedness_conflict": False,
        "cam_recheck": False,
        "validated": True,
        "notes": 'sprint + tracking blur carry shot to different environment; still sprinting at end',
        "v1_mechanism": 'traversal',
    },
    "water_bending": {
        "clips_viewed": ['water_bending_0', 'water_bending_2', 'water_bending_3'],
        "mechanism": 'transform',
        "overlay_direction": None,
        "scene_swap": True,
        "sidedness": 'two_sided',
        "camera_defining": True,
        "stylization": False,
        "middle_only": True,
        "subject_anchored": True,
        "owner_ruling": False,
        "sidedness_conflict": False,
        "cam_recheck": False,
        "validated": True,
        "conflict_resolved": 'owner 2026-07-16',
        "notes": 'water manipulated around/onto subject (RULING: accrual or substitution?)',
        "v1_mechanism": 'morph',
    },
    "water_element": {
        "clips_viewed": ['water_element_0', 'water_element_2', 'water_element_5'],
        "mechanism": 'transform',
        "overlay_direction": None,
        "scene_swap": False,
        "sidedness": 'A_only',
        "camera_defining": False,
        "stylization": False,
        "middle_only": True,
        "subject_anchored": True,
        "owner_ruling": False,
        "sidedness_conflict": False,
        "cam_recheck": False,
        "validated": True,
        "conflict_resolved": 'owner 2026-07-16',
        "notes": 'verified exemplar 2 = body->water (transform); other exemplars heterogeneous (RULING: confirm or split class; corpus: maybe not a class)',
        "v1_mechanism": 'morph',
    },
    "wireframe": {
        "clips_viewed": ['wireframe_0', 'wireframe_4', 'wireframe_8'],
        "mechanism": 'overlay',
        "overlay_direction": 'state',
        "scene_swap": False,
        "sidedness": 'A_only',
        "camera_defining": False,
        "stylization": True,
        "middle_only": False,
        "subject_anchored": False,
        "owner_ruling": False,
        "sidedness_conflict": False,
        "cam_recheck": False,
        "validated": True,
        "notes": 'subject+scene restyle to wireframe',
        "v1_mechanism": 'morph',
    },
    "wonderland": {
        "clips_viewed": ['wonderland_0', 'wonderland_2'],
        "mechanism": 'overlay',
        "overlay_direction": 'state',
        "scene_swap": False,
        "sidedness": 'A_only',
        "camera_defining": False,
        "stylization": True,
        "middle_only": False,
        "subject_anchored": False,
        "owner_ruling": False,
        "sidedness_conflict": False,
        "cam_recheck": False,
        "validated": True,
        "notes": 'whole frame restyles to stylized look',
        "v1_mechanism": 'morph',
    },
}

out = {"protocol": 'v2 rev.3 (gate-passed 2026-07-16; see docs/taxonomy/PROTOCOL_v2_PROPOSAL.md)', "classes": CLASSES}

from collections import Counter
mc = Counter(v["mechanism"] for v in CLASSES.values())
assert mc == {"transform": 17, "overlay": 12, "cover": 4, "traverse": 6}, mc
assert sum(bool(v.get("validated")) for v in CLASSES.values()) == 39
assert sum(bool(v["scene_swap"]) for v in CLASSES.values()) == 17
assert sum(bool(v["stylization"]) for v in CLASSES.values()) == 6
assert sum(bool(v["middle_only"]) for v in CLASSES.values()) == 23
assert sum(bool(v.get("owner_ruling")) for v in CLASSES.values()) == 2  # the 2 SS5.1 exceptions

OUT.write_text(yaml.safe_dump(out, sort_keys=False, allow_unicode=True, width=100))
print(f"wrote {OUT} ({len(CLASSES)} classes) — counts OK: {dict(mc)}")
